
name: Reusable Workflow 2

on:
  workflow_call:
jobs:
  ru2-job1:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3

      - name: Run a one-line script
        run: echo Hello, world!

      - name: Write something to Log
        run: |
          echo "I am Reusable Workflow Two - on Main Branch"
